### ISSUE TITLE
ローカルで`make lint`がこける（`cd backend && yarn lint`）

### ISSUE THREAD

**Issue by usatie** [usatie/pong#139]
```
➜  pong git:(backend/chat/enhanced-e2e) make lint
npm --prefix frontend run lint

> frontend@0.1.0 lint
> next lint

✔ No ESLint warnings or errors
yarn --cwd backend lint
yarn run v1.22.19
$ eslint "{src,apps,libs,test}/**/*.ts" --fix

Oops! Something went wrong! :(

ESLint: 8.55.0

TypeError: Error while loading rule '@typescript-eslint/ban-ts-comment': (0 , eslint_utils_1.getSourceCode) is not a function
Occurred while linting /Users/shunusami/Desktop/42/pong/backend/src/app.controller.spec.ts
    at create (/Users/shunusami/Desktop/42/pong/backend/node_modules/@typescript-eslint/eslint-plugin/dist/rules/ban-ts-comment.js:78:61)
    at Object.create (/Users/shunusami/Desktop/42/pong/backend/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
    at createRuleListeners (/Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:910:21)
    at /Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:1081:110
    at Array.forEach (<anonymous>)
    at runRules (/Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:1018:34)
    at Linter._verifyWithoutProcessors (/Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:1370:31)
    at Linter._verifyWithConfigArray (/Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:1822:21)
    at Linter.verify (/Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:1452:65)
    at Linter.verifyAndFix (/Users/shunusami/Desktop/42/pong/backend/node_modules/eslint/lib/linter/linter.js:2083:29)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [lint] Error 2
```

**Comment by usatie** [comment]
`yarn upgrade`したら治ったけれど、これはこれでcommitするか〜。

**Comment by usatie** [comment]
原因は謎だったので、とりあえずcloseしておく
