### ISSUE TITLE
`prisma db seed`でエラー出てる

### ISSUE THREAD

**Issue by usatie** [usatie/pong#73]
おそらく何回走っても大丈夫なseedスクリプトになっていないと思う
```
pong-backend-1  | $ /app/node_modules/.bin/prisma db seed
pong-backend-1  | Running seed command `ts-node prisma/seed.ts` ...
pong-backend-1  | {
pong-backend-1  |   user1: {
pong-backend-1  |     id: 1,
pong-backend-1  |     email: 'susami@example.com',
pong-backend-1  |     name: 'Susami',
pong-backend-1  |     password: '$2b$10$zjFFqih6OxDW3NzW5E/WdONDbMyuiIUp5lJvKu6JnezXVlX8hLKTO'
pong-backend-1  |   },
pong-backend-1  |   user2: {
pong-backend-1  |     id: 2,
pong-backend-1  |     email: 'thara@example.com',
pong-backend-1  |     name: 'Thara',
pong-backend-1  |     password: '$2b$10$0pdeP9SZIgbAJLWxagSM0.IGhCCorHQNCo5OPLjS3bTATKjRl5Zy2'
pong-backend-1  |   },
pong-backend-1  |   user3: {
pong-backend-1  |     id: 3,
pong-backend-1  |     email: 'kakiba@example.com',
pong-backend-1  |     name: 'Kakiba',
pong-backend-1  |     password: '$2b$10$bjyq1I8bxjMq7OWRY6HkteAPeui5bkgQxzwtxav.v0.aAdF.fzzy.'
pong-backend-1  |   },
pong-backend-1  |   user4: {
pong-backend-1  |     id: 4,
pong-backend-1  |     email: 'shongou@example.com',
pong-backend-1  |     name: 'Shongou',
pong-backend-1  |     password: '$2b$10$Ztd1zd6GL021vO0XdB19.eVm6aXptUOkmTsWYct75X95XAeZ2o9xi'
pong-backend-1  |   }
pong-backend-1  | }
pong-backend-1  | PrismaClientKnownRequestError:
pong-backend-1  | Invalid `prisma.room.upsert()` invocation in
pong-backend-1  | /app/prisma/seed.ts:60:35
pong-backend-1  |
pong-backend-1  |   57
pong-backend-1  |   58 console.log({ user1, user2, user3, user4 });
pong-backend-1  |   59
pong-backend-1  | → 60 const room1 = await prisma.room.upsert(
pong-backend-1  | The required connected records were not found. Expected 4 records to be connected after connect operation on one-to-many relation 'RoomTouseronroom', found 0.
pong-backend-1  |     at Cn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6817)
pong-backend-1  |     at Cn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6206)
pong-backend-1  |     at Cn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5926)
pong-backend-1  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9968)
pong-backend-1  |     at async main (/app/prisma/seed.ts:60:17) {
pong-backend-1  |   code: 'P2018',
pong-backend-1  |   clientVersion: '5.5.0',
pong-backend-1  |   meta: {
pong-backend-1  |     details: "Expected 4 records to be connected after connect operation on one-to-many relation 'RoomTouseronroom', found 0."
pong-backend-1  |   }
pong-backend-1  | }
pong-backend-1  |
pong-backend-1  | An error occurred while running the seed command:
pong-backend-1  | Error: Command failed with exit code 1: ts-node prisma/seed.ts
pong-backend-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pong-backend-1  | error Command failed with exit code 1.
```

**Comment by usatie** [comment]
これはもう直してあった
